### ISSUE TITLE
media-tv/plex-media-server @preserved-rebuild

### ISSUE THREAD

**Issue by waldo-de-kard** [megabaks/stuff#48]
http://paste.org.ru/?rutl4q
emerge @preserved-rebuild не может обновить для работы с /usr/lib/libavformat.so.54 и /usr/lib/libavcodec.so.54
После обновления до media-video/ffmpeg-2.2.3-r1

**Comment by istitov** [comment]
Я боюсь поинтересоваться, а сейчас-то все работает?

**Comment by waldo-de-kard** [comment]
А не знаю. Пользуюсь из оверлея funtoo.

**Comment by istitov** [comment]
У меня проблем не возникло.
(Наверное, многоэтажка сгорела уже...)
