### ISSUE TITLE
Invalid ebuild name

### ISSUE THREAD

**Issue by bircoph** [megabaks/stuff#58]
Hello,

tree check detected invalid ebuild name:
media-libs/alembic/openimageio-9999.ebuild

Should be:
media-libs/alembic/alembic-9999.ebuild

**Comment by RADDyomin** [comment]
Yep, it is.
 %  su -c "eclean distfiles"                                                                                                                                                                     ~ 
Password: 
 * Building file list for distfiles cleaning...

Invalid ebuild name: /mnt/portage/stuff/media-libs/alembic/openimageio-9999.ebuild
Getting this after each eclean call.

**Comment by megabaks** [comment]
fixed
