### ISSUE TITLE
media-sound/deadbeef-0.6.1 broken by new patch

### ISSUE THREAD

**Issue by stefantalpalaru** [megabaks/stuff#62]
* Applying desktop-2.patch ...

     * Failed Patch: desktop-2.patch !
     *  ( /var/lib/layman/stuff/media-sound/deadbeef/files/desktop-2.patch )
     *

**Comment by megabaks** [comment]
try now...

**Comment by stefantalpalaru** [comment]
It's fixed. Thanks.
