### ISSUE TITLE
EAPI related errors on ~amd64

### ISSUE THREAD

**Issue by stefantalpalaru** [megabaks/stuff#64]
EAPI 2/3 support is now deprecated:
- gnome-extra/indicator-applet-0.4.5
- x11-libs/libwnck-3.2.1

EAPI=4 is not supported:
- kde-base/dolphin-box-plugin-9999
- kde-misc/plasma-widget-menubar-0.1.16
- kde-misc/plasma-widget-menubar-0.1.18
- x11-libs/compizconfig-backend-kconfig4-0.8.4

**Comment by megabaks** [comment]
/me can't support it now.
sorry.
my pc dead.

**Comment by Pastafarianist** [comment]
Yeah, I'm getting lots of error messages about unsupported EAPI too. Do you intend to fix it soon (perhaps, after replacing your PC)?

**Comment by megabaks** [comment]
in the june...may be (

**Comment by istitov** [comment]
Hmmmm....  everything seems to be fixed now.
