### ISSUE TITLE
EAPI=3 error on every emerge

### ISSUE THREAD

**Issue by Pastafarianist** [megabaks/stuff#67]
Hello.

First, I must say you've done an excellent job putting together this overlay: it contains a lot of software which is nowhere else to be found. Many thanks for this.

Unfortunately, I'm getting `EAPI=3` error on every `emerge` execution. Specifically:

    * ERROR: x11-libs/libwnck-3.2.1::stuff failed (depend phase):
     *   EAPI=3 is not supported
     * 
     * Call stack:
     *              ebuild.sh, line 584:  Called source '/var/lib/layman/stuff/x11-libs/libwnck/libwnck-3.2.1.ebuild'
     *   libwnck-3.2.1.ebuild, line   9:  Called inherit 'gnome2'
     *              ebuild.sh, line 280:  Called __qa_source '/usr/portage/eclass/gnome2.eclass'
     *              ebuild.sh, line  80:  Called source '/usr/portage/eclass/gnome2.eclass'
     *          gnome2.eclass, line  19:  Called die
     * The specific snippet of code:
     *      *) die "EAPI=${EAPI} is not supported" ;;
     * 
     * If you need support, post the output of `emerge --info '=x11-libs/libwnck-3.2.1::stuff'`,
     * the complete build log and the output of `emerge -pqv '=x11-libs/libwnck-3.2.1::stuff'`.
     * Working directory: '/usr/lib64/python2.7/site-packages'
     * S: '/var/tmp/portage/x11-libs/libwnck-3.2.1/work/libwnck-3.2.1'

Could you look into the cause and see if you could fix this?

**Comment by alexws54tk** [comment]
Hello @Pastafarianist.
Subj in this https://github.com/megabaks/stuff/pull/66 pull request.

**Comment by istitov** [comment]
Should work now.
