### ISSUE TITLE
mail-client/alpine-9999, like all live ebuilds, should not be keyworded

### ISSUE THREAD

**Issue by stefantalpalaru** [megabaks/stuff#82]
It also fails on ~amd64 with:
     * ERROR: mail-client/alpine-9999::stuff failed (unpack phase):
     *   Nothing passed to the 'unpack' command

**Comment by istitov** [comment]
d3bbaac46faaa12f4eaef8c732c190df97bc9202 should close this bu, please check it out. ;-)
