### ISSUE TITLE
sys-apps/uksmstat: doesn't exist anymore

### ISSUE THREAD

**Issue by rindeal** [megabaks/stuff#84]
In favour of https://github.com/jorgicio/jorgicio-gentoo/tree/master/sys-apps/uksmtools

**Comment by istitov** [comment]
Looks like that @pfactum dropped uksmtools (as he dropped UKSM from pf-kernel).
So, I'm dropping it too.
If you point out that somebody else is supporting uskmtools, I'll add the ebuild back
