### ISSUE TITLE
mlt-9999 no longer builds

### ISSUE THREAD

**Issue by rugubara** [megabaks/stuff#85]
* Applying mlt-0.9.8-ruby-link.patch ...

 * Failed Patch: mlt-0.9.8-ruby-link.patch !
 *  ( /var/lib/layman/stuff/media-libs/mlt/files/mlt-0.9.8-ruby-link.patch )
 *
 * Include in your bugreport the contents of:
 *
 *   /var/tmp/portage/media-libs/mlt-9999/temp/mlt-0.9.8-ruby-link.patch.out

 * ERROR: media-libs/mlt-9999::stuff failed (prepare phase):
 *   Failed Patch: mlt-0.9.8-ruby-link.patch!
 *
 * Call stack:
 *     ebuild.sh, line  133:  Called src_prepare
 *   environment, line 3556:  Called epatch '/var/lib/layman/stuff/media-libs/mlt/files/mlt-0.9.8-ruby-link.patch'
 *   environment, line 1055:  Called die
 * The specific snippet of code:
 *               die "Failed Patch: ${patchname}!";
 *
 * If you need support, post the output of `emerge --info '=media-libs/mlt-9999::stuff'`,
 * the complete build log and the output of `emerge -pqv '=media-libs/mlt-9999::stuff'`.
 * The complete build log is located at '/var/tmp/portage/media-libs/mlt-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-libs/mlt-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/media-libs/mlt-9999/work/mlt-9999'
 * S: '/var/tmp/portage/media-libs/mlt-9999/work/mlt-9999'

Exerpt from the patch.out:

PATCH COMMAND:  patch -p1 -g0 -E --no-backup-if-mismatch  --dry-run -f < '/var/lib/layman/stuff/media-libs/mlt/files/mlt-0.9.8-ruby-link.patch'

=====================================
checking file src/swig/ruby/build
Hunk #1 FAILED at 5.
1 out of 1 hunk FAILED

patch program exited with status 1
=====================================

**Comment by istitov** [comment]
Should work now, sorry for the delay.
