### ISSUE TITLE
broken homepage for kde-misc/ihatethecashew

### ISSUE THREAD

**Issue by mik1osh** [megabaks/stuff#86]
homepage
http://www.kde-look.org/content/show.php/I+HATE+the+Cashew?content=91009
got a 404 error

**Comment by istitov** [comment]
Yeah, it seems moved...
Have no idea what to do with it...

**Comment by istitov** [comment]
Updated ebuild. Please check it out.

**Comment by mik1osh** [comment]
Fetching https://anongit.kde.org/ihatethecashew ...
git fetch https://anongit.kde.org/ihatethecashew +HEAD:refs/git-r3/HEAD
fatal: repository 'https://anongit.kde.org/ihatethecashew/' not found

**Comment by alexws54tk** [comment]
@mik1osh do You resync overlay?

**Comment by istitov** [comment]
@mik1osh , so did it work in the end?

**Comment by mik1osh** [comment]
```
# LANG=C eix ihate
[U] kde-misc/ihatethecashew [1]
     Available versions:  (**)9999 {debug}
     Installed versions:  0.4-r1(03:29:48 10/05/15)(-aqua -debug)
     Homepage:            https://github.com/gustavosbarreto/plasma-ihatethecashew
     Description:         KDE4 plasmoid. Removes the "hand" in upper right corner of the screen

[1] "stuff" /var/lib/layman/stuff
# emerge kde-misc/ihatethecashew | wgetpaste
Your paste can be seen here: http://bpaste.net/show/b86d37b2547a
# layman -S
# emerge kde-misc/ihatethecashew | wgetpaste
Your paste can be seen here: http://bpaste.net/show/e2964b104656
```

So yes, I resync overlay, and no, unfortunately it does has not helped :(

**Comment by alexws54tk** [comment]
Странно это как-то. Сорцы лежат на [ГитХабе](/gustavosbarreto/plasma-ihatethecashew), в ебилде так и прописано, но оно упорно тянет из старого места.

Разобрался. Оно тянет из старого места, как-будто оно часть КДЕ4.
Надо в ебилд добавить строку с правильной репой `EGIT_REPO_URI="https://github.com/gustavosbarreto/plasma-ihatethecashew.git"` переопределив тем самым источник.

По крайней мере у меня оно вытянулось, и даже начало что-то там собирать, но упало за отсутствием в системе КДЕ4.

@mik1osh this is patch [ihatethecashew-9999.ebuild.diff] (https://github.com/megabaks/stuff/files/461939/ihatethecashew-9999.ebuild.diff.txt) and new ebuild [ihatethecashew-9999.ebuild](https://github.com/megabaks/stuff/files/461946/ihatethecashew-9999.ebuild.txt)

**Comment by istitov** [comment]
Upd ebuild, works for me now... 
thnx @alexws54tk , @mik1osh check that out...

**Comment by mik1osh** [comment]
works for me, thanks for support, guys!
