### ISSUE TITLE
media-gfx/inkscape-9999 fails to build - autogen.sh not found

### ISSUE THREAD

**Issue by fordfrog** [megabaks/stuff#87]
it seems they switched the build system to cmake as both autogen.sh and configure scripts are missing and there are cmake files present in the sources

**Comment by istitov** [comment]
thanx for the upd. will check it out...

**Comment by fordfrog** [comment]
i added pull request https://github.com/megabaks/stuff/pull/89 for this issue.

**Comment by istitov** [comment]
Added. Thnx!
