### ISSUE TITLE
Fix sonata-9999.ebuild, please

### ISSUE THREAD

**Issue by spikatlinux** [megabaks/stuff#92]
I get the following error while syncing your overlay `ebuild sonata-9999.ebuild digest 
ERROR: media-sound/sonata-9999::stuff failed (depend phase):
No supported implementation in PYTHON_COMPAT.
 
Call stack:
ebuild.sh, line 606:  Called source '/var/lib/layman/stuff/media-sound/sonata/sonata-9999.ebuild'
sonata-9999.ebuild, line   8:  Called inherit 'distutils-r1' 'python-r1' 'git-r3'
ebuild.sh, line 302:  Called __qa_source '/usr/portage/eclass/distutils-r1.eclass'
 ebuild.sh, line 102:  Called source '/usr/portage/eclass/distutils-r1.eclass'
 distutils-r1.eclass, line  86:  Called inherit 'multiprocessing' 'python-r1'
 ebuild.sh, line 302:  Called __qa_source '/usr/portage/eclass/python-r1.eclass'
 ebuild.sh, line 102:  Called source '/usr/portage/eclass/python-r1.eclass'
 python-r1.eclass, line 224:  Called _python_set_globals
 python-r1.eclass, line 186:  Called _python_set_impls
 python-utils-r1.eclass, line 130:  Called die
 The specific snippet of code:
 die "No supported implementation in PYTHON_COMPAT."
  
 If you need support, post the output of `emerge --info '=media-sound/sonata-9999::stuff'`,
 the complete build log and the output of `emerge -pqv '=media-sound/sonata-9999::stuff'`.
 Working directory: '/usr/lib64/python2.7/site-packages'
 S: '/tmp/portage/media-sound/sonata-9999/work/sonata-9999'`

I edited the the `PYTHON_COMPAT=( python{3_2,3_3} )` with `PYTHON_COMPAT=( python{3_3,3_4,3_5} )` , don´t know if this is the right way, but `ebuild sonata-9999.ebuild digest` gives no error.

Regards

**Comment by DolphinStKom** [comment]
Hi! You are right, since Python has changed in version. I added this change as soon as there was a python 3.4, but forgot to change ebuild in the repository.
Thank you for the keep an eye and to voice the existing problems.
The problem is resolved.
